model: yolo11m.pt
data: ../../../training/data.yaml
project: ../outputs
name: yolov12-long
epochs: 220
imgsz: 1280
batch: 8
patience: 80
device: auto
workers: 8
optimizer: AdamW
warmup_epochs: 5
warmup_momentum: 0.8
warmup_bias_lr: 0.1
lr0: 0.0015
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
augment: true
mixup: 0.15
copy_paste: 0.2
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
mosaic: 1.0
close_mosaic: 5
scale: 0.6
perspective: 0.0005
shear: 1.0
flipud: 0.0
fliplr: 0.5
cls: 1.5
box: 7.5
overlap_mask: true
val: true
plots: true
save: true
save_period: 5
cache: ram
seed: 42
