model: yolo11n.pt
data: ../../../training/data.yaml
project: ../outputs
name: yolov12-baseline
epochs: 100
imgsz: 1280
batch: 16
patience: 40
device: auto
workers: 8
optimizer: AdamW
warmup_epochs: 3
lr0: 0.002
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
augment: true
plots: true
save_period: 10
